const PORTFOLIOS_COLLECTION_NAME = 'portfolios';
const LINKS_COLLECTION_NAME = 'links';
const PROJECTS_COLLECTION_NAME = 'projects';
const IMAGES_DIRECTORY_NAME = 'images';

export { IMAGES_DIRECTORY_NAME, LINKS_COLLECTION_NAME, PORTFOLIOS_COLLECTION_NAME, PROJECTS_COLLECTION_NAME };